/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Man.glb -T 
Files: Man.glb [493.2KB] > F:\My Documents\Sites\games\cannon\public\models\Man-transformed.glb [157.71KB] (68%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'
import { useMemo } from 'react'
import { useRef } from 'react'

const link = 'models/Man-transformed.glb'

export function Model({ action, ...props }) {
  const group = useRef()
  const { scene, animations } = useGLTF(link)
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions[action]?.reset().fadeIn(0.2).play()
    return () => actions[action]?.fadeOut(0.2)
  }, [action, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Bone} />
        <group name="BaseHuman" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh name="BaseHuman_1" geometry={nodes.BaseHuman_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_1.skeleton} />
          <skinnedMesh name="BaseHuman_2" geometry={nodes.BaseHuman_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_2.skeleton} />
          <skinnedMesh name="BaseHuman_3" geometry={nodes.BaseHuman_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_3.skeleton} />
          <skinnedMesh name="BaseHuman_4" geometry={nodes.BaseHuman_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_4.skeleton} />
          <skinnedMesh name="BaseHuman_5" geometry={nodes.BaseHuman_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_5.skeleton} />
          <skinnedMesh name="BaseHuman_6" geometry={nodes.BaseHuman_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_6.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(link)
