/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Man.glb -T 
Files: Man.glb [493.2KB] > F:\My Documents\Sites\games\cannon\public\models\Man-transformed.glb [157.71KB] (68%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'
import { useMemo } from 'react'
import { useRef } from 'react'

const link = 'models/Man-transformed.glb'

export function ModelMan({ action, ...props }) {
  const group = useRef()
  const { scene, animations } = useGLTF(link)
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const currentAction = actions ? actions[action] : null
    if (currentAction) {
      currentAction.reset().fadeIn(0.2).play()
      return () => {
        if (currentAction && typeof currentAction.fadeOut === 'function') {
          currentAction.fadeOut(0.2)
        }
      }
    }
  }, [action, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={clone} />
    </group>
  )
}

useGLTF.preload(link)
