/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Toon.glb -T 
Files: Toon.glb [68.28MB] > F:\My Documents\Sites games\cannon\public\models\Toon-transformed.glb [31.92MB] (53%)
Author: toonytoonington (https://sketchfab.com/toonytoonington)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toon-animations-rig-medium-legs-w-shorts-21892e90db3f43d8a9529858c677d92a
Title: Toon Animations Rig (medium legs w/ shorts)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModelToon({ action, ...props }) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/Toon-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const currentAction = actions ? actions[action] : null

    if (currentAction) {
      currentAction.reset().fadeIn(0.2).play()

      return () => {
        if (currentAction && typeof currentAction.fadeOut === 'function') {
          currentAction.fadeOut(0.2)
        }
      }
    }
  }, [action, actions])

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      renderOrder={10}
    >
      <group name="Sketchfab_Scene" renderOrder={10}>

        <primitive object={nodes._rootJoint} renderOrder={10} />

        <skinnedMesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.atlas2} skeleton={nodes.Object_198.skeleton} scale={0.005} renderOrder={10} />

        <skinnedMesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.atlas2} skeleton={nodes.Object_200.skeleton} scale={0.005} renderOrder={10} />

        <skinnedMesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.atlas2} skeleton={nodes.Object_202.skeleton} scale={0.005} renderOrder={10} />

      </group>
    </group>
  )
}

useGLTF.preload('models/Toon-transformed.glb')
